import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Language = "en" | "fr";

const translations = {
  en: {
    // Auth
    welcome: "Welcome to",
    appName: "Deliver LBH",
    tagline: "Fast delivery in Lubumbashi",
    signIn: "Sign In",
    signUp: "Create Account",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Full Name",
    phone: "Phone Number",
    selectRole: "I am a...",
    customer: "Customer",
    restaurantOwner: "Restaurant Owner",
    driver: "Delivery Driver",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    forgotPassword: "Forgot password?",
    continueAs: "Continue as",
    logout: "Log out",

    // Driver onboarding
    vehicleType: "Vehicle Type",
    vehicleMoto: "Moto",
    vehicleBicycle: "Bicycle",
    vehicleCar: "Car",
    vehicleFoot: "On Foot",
    driverPendingTitle: "Application Under Review",
    driverPendingDesc: "Your driver application has been received and is being reviewed by our team. You'll be ready to start deliveries once approved.",
    driverRejectedTitle: "Application Not Approved",
    driverRejectedDesc: "Your application was not approved. Please contact support at support@deliverlbh.com for more information.",
    driverStep1: "Account created successfully",
    driverStep2: "Application under review by team",
    driverStep3: "Start taking deliveries",
    driverCheckStatus: "Check approval status",

    // Payment — providers & status
    selectProvider: "Choose your provider",
    mPesa: "M-Pesa",
    airtelMoney: "Airtel Money",
    paymentSubmitted: "Reference Submitted",
    paymentConfirmed: "Payment Confirmed",
    paymentFailed: "Payment Failed",
    paymentPaid: "Paid",
    paymentPendingLabel: "Awaiting Reference",
    paymentProvider: "Provider",
    paymentPhone: "Payment Phone",
    paymentConfirmedAt: "Reviewed on",
    paymentRequestedAt: "Submitted on",
    // Submit reference card (order screen)
    submitRefTitle: "Submit Payment Reference",
    submitRefDesc: "Send the amount via M-Pesa or Airtel, then enter your transaction reference below for verification.",
    submitRefUpdate: "Update Reference",
    transactionRef: "Transaction reference",
    submitRefBtn: "Submit Reference",
    submitRefSuccess: "Reference submitted successfully",
    awaitingReview: "Awaiting admin review",
    refAlreadyReviewed: "This payment has already been reviewed",
    // Checkout info text updates
    mobileMoneyDesc: "Pay via M-Pesa or Airtel Money. You can also submit your reference after placing the order.",
    mobileMoneyRefOptional: "Reference (optional — can be added after)",

    // Push notification alerts
    pushNewOrder: "New Order",
    pushNewOrderDesc: "A new order is waiting for your confirmation",
    pushNewOrderDescPlural: "new orders are waiting for your confirmation",
    pushStatusChanged: "Order Updated",
    pushStatusChangedDesc: "Your order status has changed",
    pushDriverAccepted: "Driver On the Way!",
    pushDriverAcceptedDesc: "A driver has picked up your order",
    pushDelivered: "Order Delivered!",
    pushDeliveredDesc: "Your order has been delivered. Enjoy your meal!",

    // Home
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    deliverTo: "Deliver to",
    searchRestaurants: "Search restaurants...",
    categories: "Categories",
    topRated: "Top Rated",
    nearYou: "Near You",
    allRestaurants: "All Restaurants",
    featured: "Featured",
    free: "Free",
    min: "min",

    // Restaurant
    menu: "Menu",
    addToCart: "Add to Cart",
    added: "Added",
    viewCart: "View Cart",
    open: "Open",
    closed: "Closed",
    rating: "Rating",
    delivery: "Delivery",
    noItems: "No items available",

    // Cart & Checkout
    yourCart: "Your Cart",
    emptyCart: "Your cart is empty",
    emptyCartDesc: "Add items from a restaurant to get started",
    browseRestaurants: "Browse Restaurants",
    subtotal: "Subtotal",
    deliveryFee: "Delivery Fee",
    total: "Total",
    paymentMethod: "Payment Method",
    cashOnDelivery: "Cash on Delivery",
    mobileMoney: "Mobile Money",
    mobileMoneyDesc: "You will pay via M-Pesa / Airtel Money",
    mobileMoneyPhone: "Mobile money phone number",
    mobileMoneyRef: "Transaction reference (optional)",
    deliveryAddress: "Delivery Address",
    savedAddresses: "Saved Addresses",
    addNewAddress: "Add new address",
    saveAddress: "Save this address",
    enterAddress: "Enter delivery address",
    addressLabel: "Label (e.g. Home, Work)",
    driverInstructions: "Instructions for driver",
    driverInstructionsPlaceholder: "e.g. Gate code 1234, call on arrival",
    addNote: "Add a note for the restaurant (optional)",
    placeOrder: "Place Order",
    orderPlaced: "Order Placed!",
    orderPlacedDesc: "Your order has been received. Track it in My Orders.",
    orderError: "Failed to place order",
    phoneRequired: "Phone number is required",
    addressRequired: "Delivery address is required",
    invalidPhone: "Enter a valid phone number (min 9 digits)",

    // Orders
    myOrders: "My Orders",
    noOrders: "No orders yet",
    noOrdersDesc: "Your order history will appear here",
    pending: "Pending",
    confirmed: "Confirmed",
    preparing: "Preparing",
    readyForPickup: "Ready for Pickup",
    pickedUp: "Picked Up",
    delivered: "Delivered",
    cancelled: "Cancelled",
    orderDetails: "Order Details",
    trackOrder: "Track order",
    reorder: "Reorder",
    paymentStatus: "Payment Status",
    paymentPending: "Pending",
    paymentPaid: "Paid",
    paymentRef: "Reference",
    customerPhone: "Customer Phone",
    orderNotes: "Order Notes",
    driverNote: "Driver Instructions",

    // Driver
    availableOrders: "Available Orders",
    myDeliveries: "My Deliveries",
    noAvailableOrders: "No orders available",
    noAvailableDesc: "Check back soon for new orders",
    pickUp: "Accept & Pick Up",
    markDelivered: "Mark as Delivered",
    earnings: "Earnings",

    // Restaurant owner
    dashboard: "Dashboard",
    myRestaurant: "My Restaurant",
    addItem: "Add Item",
    editItem: "Edit Item",
    todayOrders: "Active Orders",
    newOrder: "New Order",
    confirmOrder: "Confirm Order",
    startPreparing: "Start Preparing",
    readyForDriver: "Ready for Driver",
    totalRevenue: "Revenue",
    // Restaurant profile
    restaurantProfile: "My Restaurant",
    restaurantSettings: "Restaurant Settings",
    restaurantInfo: "Restaurant Info",
    restaurantStatus: "Status",
    restaurantOpen: "Open",
    restaurantClosed: "Closed",
    restaurantOpenToggle: "Restaurant is open",
    restaurantClosedToggle: "Restaurant is closed",
    openingHours: "Opening Hours",
    openingHoursPlaceholder: "e.g. Mon–Fri 08:00–22:00",
    deliveryTime: "Delivery Time (min)",
    deliveryTimePlaceholder: "e.g. 30",
    deliveryFee: "Delivery Fee (CDF)",
    deliveryFeePlaceholder: "e.g. 2000",
    restaurantCategory: "Category",
    restaurantImageUrl: "Cover Image URL (optional)",
    restaurantSaved: "Restaurant updated",
    restaurantSaveError: "Failed to save changes",
    nameMin: "Name must not be empty",
    phoneMin: "Phone number required",
    addressMin: "Address required",
    deliveryFeeMin: "Delivery fee must be 0 or more",
    deliveryTimeMin2: "Delivery time must be at least 1 minute",
    unsavedChanges: "Unsaved changes",
    discardChanges: "Discard changes",
    discardChangesDesc: "You have unsaved changes. Are you sure you want to leave?",
    keepEditing: "Keep editing",
    discard: "Discard",

    // Menu management
    menuManagement: "Menu",
    menuItems: "Menu Items",
    noMenuItems: "No items yet",
    noMenuItemsDesc: "Add your first menu item to get started",
    addFirstItem: "Add First Item",
    noRestaurant: "No Restaurant Found",
    noRestaurantDesc: "You haven't created a restaurant yet. Contact support.",
    itemName: "Item Name",
    itemNamePlaceholder: "e.g. Pizza Margherita",
    itemDescription: "Description (optional)",
    itemDescriptionPlaceholder: "Describe this dish...",
    itemPrice: "Price (CDF)",
    itemPricePlaceholder: "e.g. 12000",
    itemCategory: "Category",
    itemCategoryPlaceholder: "e.g. Pizzas, Drinks, Desserts",
    itemImageUrl: "Image URL (optional)",
    itemImageUrlPlaceholder: "https://...",
    itemAvailable: "Available",
    itemUnavailable: "Unavailable",
    itemSaved: "Item saved",
    itemDeleted: "Item deleted",
    deleteItemTitle: "Delete Item?",
    deleteItemConfirm: "This item will be permanently removed from your menu.",
    nameRequired: "Item name is required",
    priceRequired: "Price must be greater than 0",
    categoryRequired: "Category is required",
    available: "Available",
    unavailable: "Unavailable",
    itemsCount: "items",

    // Profile
    profile: "Profile",
    editProfile: "Edit Profile",
    address: "Address",
    save: "Save",
    saved: "Saved",
    cancel: "Cancel",
    language: "Language",
    english: "English",
    french: "French",
    settings: "Settings",
    manageAddresses: "Manage Addresses",
    noSavedAddresses: "No saved addresses",

    // Notifications
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    noNotificationsDesc: "You'll see order updates and alerts here",
    markAllRead: "Mark all as read",
    justNow: "Just now",
    minutesAgo: "min ago",
    hoursAgo: "h ago",
    yesterday: "Yesterday",

    // Driver dialogs
    acceptDeliveryMsg: "Accept and take this delivery?",
    confirmDeliveryMsg: "Confirm delivery?",

    // Notifications
    unreadNotif: "unread",
    orderRef: "Order",
    moreItems: "more",

    // Auth errors
    accountDisabled: "Account Disabled",

    // Welcome screen features
    fastDelivery: "Fast delivery",
    bestRestaurants: "Best restaurants",
    realTimeTracking: "Real-time tracking",

    // Legal & Support
    legalSupport: "Legal & Support",
    privacyPolicy: "Privacy Policy",
    supportContact: "Support & Contact",
    appVersion: "Version",
    privacyPolicyTitle: "Privacy Policy",
    privacyPolicyIntro: "Deliver LBH is committed to protecting your privacy. This policy explains what data we collect and how we use it.",
    privacyDataTitle: "Data We Collect",
    privacyDataItems: "• Name, email, and phone number (account creation)\n• Delivery addresses (to process orders)\n• Order history (to display your past orders)\n• Device information (to provide the service)",
    privacyUseTitle: "How We Use Your Data",
    privacyUseItems: "• To process and deliver your orders\n• To contact you about your orders\n• To improve the service\n• We do not sell your data to third parties.",
    privacyPaymentTitle: "Payment Information",
    privacyPaymentItems: "Cash payments and Mobile Money (M-Pesa / Airtel) references are recorded for order tracking only. We do not store card numbers or mobile banking credentials.",
    privacyContactTitle: "Contact Us",
    privacyContactText: "For any questions about this policy, contact us at:",
    privacyUpdatedText: "Last updated: March 2026",
    supportTitle: "Support & Contact",
    supportSubtitle: "We're here to help",
    supportEmailLabel: "Email Support",
    supportEmailValue: "support@deliverlbh.com",
    supportWhatsAppLabel: "WhatsApp",
    supportWhatsAppValue: "+243 81 000 0000",
    supportFaqTitle: "Frequently Asked Questions",
    supportFaq1Q: "How do I track my order?",
    supportFaq1A: "Go to the Orders tab and tap on your active order to see its current status in real time.",
    supportFaq2Q: "What payment methods are accepted?",
    supportFaq2A: "We accept cash on delivery and Mobile Money (M-Pesa / Airtel Money).",
    supportFaq3Q: "Can I cancel an order?",
    supportFaq3A: "Orders can only be cancelled before they are confirmed by the restaurant. Contact us immediately if you need to cancel.",
    supportFaq4Q: "My order is late. What do I do?",
    supportFaq4A: "Check the order status in the app. If the delay is unusual, contact us via WhatsApp or email and we will assist you.",
    supportFaq5Q: "How do I become a delivery driver?",
    supportFaq5A: "Register in the app and select 'Delivery Driver' as your role. Our team will verify your account.",

    // Common
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    back: "Back",
    items: "items",
    item: "item",
    currency: "CDF",
    itemCount: "items in cart",
    success: "Success",
    delete: "Delete",
    confirm: "Confirm",
  },
  fr: {
    // Auth
    welcome: "Bienvenue sur",
    appName: "Deliver LBH",
    tagline: "Livraison rapide à Lubumbashi",
    signIn: "Se connecter",
    signUp: "Créer un compte",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    name: "Nom complet",
    phone: "Numéro de téléphone",
    selectRole: "Je suis...",
    customer: "Client",
    restaurantOwner: "Propriétaire de restaurant",
    driver: "Livreur",
    alreadyHaveAccount: "Déjà un compte?",
    dontHaveAccount: "Pas encore de compte?",
    forgotPassword: "Mot de passe oublié?",
    continueAs: "Continuer en tant que",
    logout: "Déconnexion",

    // Driver onboarding
    vehicleType: "Type de véhicule",
    vehicleMoto: "Moto",
    vehicleBicycle: "Vélo",
    vehicleCar: "Voiture",
    vehicleFoot: "À pied",
    driverPendingTitle: "Candidature en cours d'examen",
    driverPendingDesc: "Votre candidature de livreur a été reçue et est examinée par notre équipe. Vous pourrez commencer les livraisons une fois approuvé.",
    driverRejectedTitle: "Candidature non approuvée",
    driverRejectedDesc: "Votre candidature n'a pas été approuvée. Veuillez contacter le support à support@deliverlbh.com pour plus d'informations.",
    driverStep1: "Compte créé avec succès",
    driverStep2: "Candidature en cours d'examen",
    driverStep3: "Commencer les livraisons",
    driverCheckStatus: "Vérifier le statut",

    // Payment — providers & status
    selectProvider: "Choisir le fournisseur",
    mPesa: "M-Pesa",
    airtelMoney: "Airtel Money",
    paymentSubmitted: "Référence soumise",
    paymentConfirmed: "Paiement confirmé",
    paymentFailed: "Paiement échoué",
    paymentPaid: "Payé",
    paymentPendingLabel: "En attente de référence",
    paymentProvider: "Fournisseur",
    paymentPhone: "Téléphone de paiement",
    paymentConfirmedAt: "Examiné le",
    paymentRequestedAt: "Soumis le",
    // Submit reference card (order screen)
    submitRefTitle: "Soumettre la référence",
    submitRefDesc: "Envoyez le montant via M-Pesa ou Airtel, puis saisissez votre référence de transaction ci-dessous pour vérification.",
    submitRefUpdate: "Mettre à jour la référence",
    transactionRef: "Référence de transaction",
    submitRefBtn: "Soumettre",
    submitRefSuccess: "Référence soumise avec succès",
    awaitingReview: "En attente de vérification",
    refAlreadyReviewed: "Ce paiement a déjà été examiné",
    // Checkout info text updates
    mobileMoneyDesc: "Payez via M-Pesa ou Airtel Money. Vous pouvez aussi soumettre votre référence après la commande.",
    mobileMoneyRefOptional: "Référence (optionnelle — peut être ajoutée après)",

    // Push notification alerts
    pushNewOrder: "Nouvelle commande",
    pushNewOrderDesc: "Une nouvelle commande attend votre confirmation",
    pushNewOrderDescPlural: "nouvelles commandes attendent votre confirmation",
    pushStatusChanged: "Commande mise à jour",
    pushStatusChangedDesc: "Le statut de votre commande a changé",
    pushDriverAccepted: "Livreur en route !",
    pushDriverAcceptedDesc: "Un livreur a pris en charge votre commande",
    pushDelivered: "Commande livrée !",
    pushDeliveredDesc: "Votre commande a été livrée. Bon appétit !",

    // Home
    goodMorning: "Bonjour",
    goodAfternoon: "Bon après-midi",
    goodEvening: "Bonsoir",
    deliverTo: "Livrer à",
    searchRestaurants: "Rechercher des restaurants...",
    categories: "Catégories",
    topRated: "Les mieux notés",
    nearYou: "Près de vous",
    allRestaurants: "Tous les restaurants",
    featured: "En vedette",
    free: "Gratuit",
    min: "min",

    // Restaurant
    menu: "Menu",
    addToCart: "Ajouter au panier",
    added: "Ajouté",
    viewCart: "Voir le panier",
    open: "Ouvert",
    closed: "Fermé",
    rating: "Note",
    delivery: "Livraison",
    noItems: "Aucun article disponible",

    // Cart & Checkout
    yourCart: "Votre panier",
    emptyCart: "Votre panier est vide",
    emptyCartDesc: "Ajoutez des articles d'un restaurant pour commencer",
    browseRestaurants: "Parcourir les restaurants",
    subtotal: "Sous-total",
    deliveryFee: "Frais de livraison",
    total: "Total",
    paymentMethod: "Mode de paiement",
    cashOnDelivery: "Paiement à la livraison",
    mobileMoney: "Mobile Money",
    mobileMoneyDesc: "Vous paierez via M-Pesa / Airtel Money",
    mobileMoneyPhone: "Numéro Mobile Money",
    mobileMoneyRef: "Référence de transaction (optionnel)",
    deliveryAddress: "Adresse de livraison",
    savedAddresses: "Adresses enregistrées",
    addNewAddress: "Nouvelle adresse",
    saveAddress: "Enregistrer cette adresse",
    enterAddress: "Entrez l'adresse de livraison",
    addressLabel: "Libellé (ex: Maison, Travail)",
    driverInstructions: "Instructions pour le livreur",
    driverInstructionsPlaceholder: "ex: Code portail 1234, appeler à l'arrivée",
    addNote: "Note pour le restaurant (optionnel)",
    placeOrder: "Passer la commande",
    orderPlaced: "Commande passée !",
    orderPlacedDesc: "Votre commande a été reçue. Suivez-la dans Mes commandes.",
    orderError: "Échec de la commande",
    phoneRequired: "Le numéro de téléphone est requis",
    addressRequired: "L'adresse de livraison est requise",
    invalidPhone: "Entrez un numéro valide (min 9 chiffres)",

    // Orders
    myOrders: "Mes commandes",
    noOrders: "Aucune commande",
    noOrdersDesc: "L'historique de vos commandes apparaîtra ici",
    pending: "En attente",
    confirmed: "Confirmé",
    preparing: "En préparation",
    readyForPickup: "Prêt pour la collecte",
    pickedUp: "Collecté",
    delivered: "Livré",
    cancelled: "Annulé",
    orderDetails: "Détails de la commande",
    trackOrder: "Suivre la commande",
    reorder: "Recommander",
    paymentStatus: "Statut du paiement",
    paymentPending: "En attente",
    paymentPaid: "Payé",
    paymentRef: "Référence",
    customerPhone: "Téléphone client",
    orderNotes: "Notes de commande",
    driverNote: "Instructions livreur",

    // Driver
    availableOrders: "Commandes disponibles",
    myDeliveries: "Mes livraisons",
    noAvailableOrders: "Aucune commande disponible",
    noAvailableDesc: "Revenez bientôt pour de nouvelles commandes",
    pickUp: "Accepter & Prendre",
    markDelivered: "Marquer comme livré",
    earnings: "Gains",

    // Restaurant owner
    dashboard: "Tableau de bord",
    myRestaurant: "Mon restaurant",
    addItem: "Ajouter un article",
    editItem: "Modifier l'article",
    todayOrders: "Commandes actives",
    newOrder: "Nouvelle commande",
    confirmOrder: "Confirmer la commande",
    startPreparing: "Commencer la préparation",
    readyForDriver: "Prêt pour le livreur",
    totalRevenue: "Revenu",
    // Restaurant profile
    restaurantProfile: "Mon Restaurant",
    restaurantSettings: "Paramètres du restaurant",
    restaurantInfo: "Informations",
    restaurantStatus: "Statut",
    restaurantOpen: "Ouvert",
    restaurantClosed: "Fermé",
    restaurantOpenToggle: "Le restaurant est ouvert",
    restaurantClosedToggle: "Le restaurant est fermé",
    openingHours: "Horaires d'ouverture",
    openingHoursPlaceholder: "ex: Lun–Ven 08h–22h",
    deliveryTime: "Délai de livraison (min)",
    deliveryTimePlaceholder: "ex: 30",
    deliveryFee: "Frais de livraison (CDF)",
    deliveryFeePlaceholder: "ex: 2000",
    restaurantCategory: "Catégorie",
    restaurantImageUrl: "URL de l'image de couverture (optionnel)",
    restaurantSaved: "Restaurant mis à jour",
    restaurantSaveError: "Échec de la sauvegarde",
    nameMin: "Le nom ne peut pas être vide",
    phoneMin: "Numéro de téléphone requis",
    addressMin: "Adresse requise",
    deliveryFeeMin: "Les frais de livraison doivent être ≥ 0",
    deliveryTimeMin2: "Le délai minimum est 1 minute",
    unsavedChanges: "Modifications non sauvegardées",
    discardChanges: "Ignorer les modifications",
    discardChangesDesc: "Vous avez des modifications non sauvegardées. Continuer ?",
    keepEditing: "Continuer à modifier",
    discard: "Ignorer",

    // Menu management
    menuManagement: "Menu",
    menuItems: "Articles du menu",
    noMenuItems: "Aucun article",
    noMenuItemsDesc: "Ajoutez votre premier article pour commencer",
    addFirstItem: "Ajouter le premier article",
    noRestaurant: "Aucun restaurant trouvé",
    noRestaurantDesc: "Vous n'avez pas encore de restaurant. Contactez le support.",
    itemName: "Nom de l'article",
    itemNamePlaceholder: "ex: Pizza Margherita",
    itemDescription: "Description (optionnel)",
    itemDescriptionPlaceholder: "Décrivez ce plat...",
    itemPrice: "Prix (CDF)",
    itemPricePlaceholder: "ex: 12000",
    itemCategory: "Catégorie",
    itemCategoryPlaceholder: "ex: Pizzas, Boissons, Desserts",
    itemImageUrl: "URL de l'image (optionnel)",
    itemImageUrlPlaceholder: "https://...",
    itemAvailable: "Disponible",
    itemUnavailable: "Indisponible",
    itemSaved: "Article enregistré",
    itemDeleted: "Article supprimé",
    deleteItemTitle: "Supprimer l'article ?",
    deleteItemConfirm: "Cet article sera définitivement supprimé de votre menu.",
    nameRequired: "Le nom de l'article est requis",
    priceRequired: "Le prix doit être supérieur à 0",
    categoryRequired: "La catégorie est requise",
    available: "Disponible",
    unavailable: "Indisponible",
    itemsCount: "articles",

    // Profile
    profile: "Profil",
    editProfile: "Modifier le profil",
    address: "Adresse",
    save: "Sauvegarder",
    saved: "Sauvegardé",
    cancel: "Annuler",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    settings: "Paramètres",
    manageAddresses: "Gérer les adresses",
    noSavedAddresses: "Aucune adresse enregistrée",

    // Notifications
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    noNotificationsDesc: "Les mises à jour de vos commandes apparaîtront ici",
    markAllRead: "Tout marquer comme lu",
    justNow: "À l'instant",
    minutesAgo: "min",
    hoursAgo: "h",
    yesterday: "Hier",

    // Driver dialogs
    acceptDeliveryMsg: "Accepter et prendre en charge cette livraison ?",
    confirmDeliveryMsg: "Confirmer la livraison ?",

    // Notifications
    unreadNotif: "non lue(s)",
    orderRef: "Commande",
    moreItems: "de plus",

    // Auth errors
    accountDisabled: "Compte désactivé",

    // Welcome screen features
    fastDelivery: "Livraison rapide",
    bestRestaurants: "Meilleurs restaurants",
    realTimeTracking: "Suivi en temps réel",

    // Legal & Support
    legalSupport: "Légal & Support",
    privacyPolicy: "Politique de confidentialité",
    supportContact: "Support & Contact",
    appVersion: "Version",
    privacyPolicyTitle: "Politique de confidentialité",
    privacyPolicyIntro: "Deliver LBH s'engage à protéger votre vie privée. Cette politique explique les données que nous collectons et comment nous les utilisons.",
    privacyDataTitle: "Données collectées",
    privacyDataItems: "• Nom, email et numéro de téléphone (création de compte)\n• Adresses de livraison (pour traiter vos commandes)\n• Historique des commandes (pour afficher vos commandes passées)\n• Informations sur l'appareil (pour fournir le service)",
    privacyUseTitle: "Utilisation de vos données",
    privacyUseItems: "• Pour traiter et livrer vos commandes\n• Pour vous contacter au sujet de vos commandes\n• Pour améliorer le service\n• Nous ne vendons pas vos données à des tiers.",
    privacyPaymentTitle: "Informations de paiement",
    privacyPaymentItems: "Les paiements en espèces et les références Mobile Money (M-Pesa / Airtel) sont enregistrés uniquement pour le suivi des commandes. Nous ne stockons pas les numéros de carte ni les identifiants bancaires.",
    privacyContactTitle: "Nous contacter",
    privacyContactText: "Pour toute question concernant cette politique, contactez-nous à :",
    privacyUpdatedText: "Dernière mise à jour : mars 2026",
    supportTitle: "Support & Contact",
    supportSubtitle: "Nous sommes là pour vous aider",
    supportEmailLabel: "Assistance par email",
    supportEmailValue: "support@deliverlbh.com",
    supportWhatsAppLabel: "WhatsApp",
    supportWhatsAppValue: "+243 81 000 0000",
    supportFaqTitle: "Questions fréquentes",
    supportFaq1Q: "Comment suivre ma commande ?",
    supportFaq1A: "Rendez-vous dans l'onglet Commandes et appuyez sur votre commande en cours pour voir son statut en temps réel.",
    supportFaq2Q: "Quels modes de paiement sont acceptés ?",
    supportFaq2A: "Nous acceptons le paiement à la livraison et le Mobile Money (M-Pesa / Airtel Money).",
    supportFaq3Q: "Puis-je annuler une commande ?",
    supportFaq3A: "Les commandes ne peuvent être annulées qu'avant leur confirmation par le restaurant. Contactez-nous immédiatement si vous devez annuler.",
    supportFaq4Q: "Ma commande est en retard. Que faire ?",
    supportFaq4A: "Vérifiez le statut de la commande dans l'application. Si le retard est inhabituel, contactez-nous via WhatsApp ou par email.",
    supportFaq5Q: "Comment devenir livreur ?",
    supportFaq5A: "Inscrivez-vous dans l'application et sélectionnez 'Livreur' comme rôle. Notre équipe vérifiera votre compte.",

    // Common
    loading: "Chargement...",
    error: "Une erreur s'est produite",
    retry: "Réessayer",
    back: "Retour",
    items: "articles",
    item: "article",
    currency: "CDF",
    itemCount: "articles dans le panier",
    success: "Succès",
    delete: "Supprimer",
    confirm: "Confirmer",
  },
};

type TranslationKeys = keyof typeof translations.en;

interface LangContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys) => string;
}

const LangContext = createContext<LangContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    AsyncStorage.getItem("app_language").then(saved => {
      if (saved === "en" || saved === "fr") setLanguageState(saved);
    }).catch(() => {});
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem("app_language", lang).catch(() => {});
  };

  const t = (key: TranslationKeys): string => translations[language][key] ?? key;

  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
